import { supabase } from "./supabase.js";

/* ================= LOAD PROJECTS ================= */
async function loadProjects() {
  const { data, error } = await supabase
    .from("projects")
    .select("id, project_name");

  if (error) {
    alert("Project load error");
    console.error(error);
    return;
  }

  const sel = document.getElementById("project");
  sel.innerHTML = `<option value="">-- Select Project --</option>`;

  data.forEach(p => {
    const o = document.createElement("option");
    o.value = p.id;
    o.text = p.project_name;
    sel.appendChild(o);
  });
}

/* ================= TEMP BAND ================= */
function getTempBand(temp) {
  if (temp > 260) return "HIGH";
  if (temp >= 120) return "MEDIUM";
  return "LOW";
}

/* ================= AUTO LOOP ================= */
async function getOrCreateLoop(input) {

  const tempBand = getTempBand(input.temperature);

  const { data: loops, error } = await supabase
    .from("corrosion_loops")
    .select("*")
    .eq("project_id", input.project_id)
    .eq("fluid", input.fluid)
    .eq("phase", input.phase)
    .eq("sulfur", input.sulfur)
    .eq("chloride", input.chloride)
    .eq("temp_band", tempBand);

  if (error) {
    alert("Loop search error");
    throw error;
  }

  if (loops.length > 0) return loops[0];

  const { data: loop, error: insertError } = await supabase
    .from("corrosion_loops")
    .insert([{
      project_id: input.project_id,
      loop_name: `${input.unit} ${tempBand} TEMP LOOP`,
      fluid: input.fluid,
      phase: input.phase,
      temp_band: tempBand,
      sulfur: input.sulfur,
      chloride: input.chloride
    }])
    .select()
    .single();

  if (insertError) {
    alert("Loop create failed");
    throw insertError;
  }

  return loop;
}

/* ================= AUTO DAMAGE ================= */
async function autoGenerateDamage(circuit_id) {
  const { error } = await supabase.rpc(
    "auto_damage_for_circuit",
    { cid: circuit_id }
  );

  if (error) {
    console.error("Auto damage error:", error);
    alert("Auto damage failed");
  }
}

/* ================= SAVE ALL ================= */
window.saveAll = async function () {
  try {
    const project_id = project.value;
    if (!project_id) {
      alert("Select project");
      return;
    }

    const temperature = Number(temp.value);

    /* LOOP INPUT */
    const loopInput = {
      project_id,
      unit: unit.value,
      fluid: fluid.value,
      phase: phase.value,
      temperature,
      sulfur: sulfur.checked,
      chloride: chloride.checked
    };

    /* AUTO LOOP */
    const loop = await getOrCreateLoop(loopInput);

    /* AUTO CIRCUIT */
    const { data: circuit, error: circuitError } = await supabase
      .from("circuits")
      .insert([{
        loop_id: loop.id,
        circuit_name: equipment.value,
        material: material.value,
        temperature,
        sulfur: sulfur.checked,
        chloride: chloride.checked,
        design_thickness: Number(design_thk.value),
        minimum_thickness: Number(min_thk.value)
      }])
      .select()
      .single();

    if (circuitError) {
      alert("Circuit save failed");
      console.error(circuitError);
      return;
    }

    /* AUTO DAMAGE (API 970) */
    await autoGenerateDamage(circuit.id);

    alert("✅ Loop, Circuit & API 970 Damage generated successfully");

  } catch (err) {
    console.error(err);
    alert("Unexpected error occurred");
  }
};

loadProjects();
