import { supabase } from "./supabase.js";

/* ================= LOAD PROJECTS ================= */
async function loadProjects() {
  const { data, error } = await supabase
    .from("projects")
    .select("id, project_name")
    .order("project_name");

  if (error) {
    alert("❌ Failed to load projects");
    console.error(error);
    return;
  }

  const sel = document.getElementById("project");
  sel.innerHTML = `<option value="">-- Select Project --</option>`;

  data.forEach(p => {
    const o = document.createElement("option");
    o.value = p.id;
    o.textContent = p.project_name;
    sel.appendChild(o);
  });
}

/* ================= TEMPERATURE BAND ================= */
function getTempBand(temp) {
  if (temp > 260) return "HIGH";
  if (temp >= 120) return "MEDIUM";
  return "LOW";
}

/* ================= AUTO LOOP LOGIC ================= */
async function getOrCreateLoop(input) {
  const tempBand = getTempBand(input.temperature);

  const { data: loops, error } = await supabase
    .from("corrosion_loops")
    .select("*")
    .eq("project_id", input.project_id)
    .eq("fluid", input.fluid)
    .eq("phase", input.phase)
    .eq("sulfur", input.sulfur)
    .eq("chloride", input.chloride)
    .eq("temp_band", tempBand)
    .limit(1);

  if (error) {
    console.error("Loop search error:", error);
    throw error;
  }

  /* EXISTING LOOP */
  if (loops && loops.length > 0) {
    return loops[0];
  }

  /* CREATE NEW LOOP */
  const { data: loop, error: insertError } = await supabase
    .from("corrosion_loops")
    .insert([{
      project_id: input.project_id,
      loop_name: `${input.unit} ${tempBand} TEMP LOOP`,
      fluid: input.fluid,
      phase: input.phase,
      temp_band: tempBand,
      sulfur: input.sulfur,
      chloride: input.chloride
    }])
    .select()
    .single();

  if (insertError) {
    console.error("Loop insert error:", insertError);
    throw insertError;
  }

  return loop;
}

/* ================= AUTO DAMAGE (API RP 970) ================= */
async function autoGenerateDamage(circuit_id) {
  const { error } = await supabase.rpc(
    "auto_damage_for_circuit",
    { cid: circuit_id }
  );

  if (error) {
    console.error("Auto damage error:", error);
    alert("⚠️ Circuit saved but auto-damage failed");
  }
}

/* ================= SAVE ALL ================= */
window.saveAll = async function () {
  try {
    const project_id = document.getElementById("project").value;
    if (!project_id) {
      alert("Select a project");
      return;
    }

    const temperature = Number(document.getElementById("temp").value);
    if (!temperature) {
      alert("Enter temperature");
      return;
    }

    /* LOOP INPUT */
    const loopInput = {
      project_id,
      unit: document.getElementById("unit").value,
      fluid: document.getElementById("fluid").value,
      phase: document.getElementById("phase").value,
      temperature,
      sulfur: document.getElementById("sulfur").checked,
      chloride: document.getElementById("chloride").checked
    };

    /* AUTO LOOP */
    const loop = await getOrCreateLoop(loopInput);

    if (!loop || !loop.id) {
      alert("❌ Loop creation failed");
      return;
    }

    /* AUTO CIRCUIT */
    const { data: circuit, error: circuitError } = await supabase
      .from("circuits")
      .insert([{
        loop_id: loop.id,
        circuit_name: document.getElementById("equipment").value,
        material: document.getElementById("material").value,
        temperature,
        sulfur: loopInput.sulfur,
        chloride: loopInput.chloride,
        design_thickness: Number(document.getElementById("design_thk").value),
        minimum_thickness: Number(document.getElementById("min_thk").value)
      }])
      .select()
      .single();

    if (circuitError) {
      console.error("Circuit insert error:", circuitError);
      alert("❌ Circuit save failed");
      return;
    }

    /* AUTO DAMAGE */
    await autoGenerateDamage(circuit.id);

    alert("✅ Loop, Circuit & API 970 Damage generated successfully");

  } catch (err) {
    console.error("SAVE ERROR:", err);
    alert("❌ Unexpected error occurred");
  }
};

/* INIT */
loadProjects();
