import { supabase } from "./supabase.js";

/* ================= LOAD PROJECTS ================= */
async function loadProjects() {
  const { data, error } = await supabase
    .from("projects")
    .select("id, project_name")
    .order("project_name");

  if (error) {
    alert("❌ Failed to load projects");
    console.error(error);
    return;
  }

  const sel = document.getElementById("project");
  sel.innerHTML = `<option value="">-- Select Project --</option>`;

  data.forEach(p => {
    const o = document.createElement("option");
    o.value = p.id;
    o.textContent = p.project_name;
    sel.appendChild(o);
  });
}

/* ================= TEMPERATURE BAND + RANGE ================= */
function getTempBandRange(temp) {
  if (temp <= 120) {
    return { band: "LOW", min: 0, max: 120 };
  }
  if (temp <= 260) {
    return { band: "MEDIUM", min: 121, max: 260 };
  }
  return { band: "HIGH", min: 261, max: 1000 };
}

/* ================= AUTO LOOP LOGIC ================= */
async function getOrCreateLoop(input) {
  const tempInfo = getTempBandRange(input.temperature);

  /* SEARCH EXISTING LOOP */
  const { data: loops, error } = await supabase
    .from("corrosion_loops")
    .select("id, loop_name")
    .eq("project_id", input.project_id)
    .eq("fluid", input.fluid)
    .eq("phase", input.phase)
    .eq("temp_band", tempInfo.band)
    .eq("sulfur", input.sulfur)
    .eq("chloride", input.chloride)
    .limit(1);

  if (error) {
    console.error("Loop search error:", error);
    throw error;
  }

  if (loops && loops.length > 0) {
    return loops[0];
  }

  /* CREATE NEW LOOP */
  const payload = {
    project_id: input.project_id,
    loop_name: `${input.unit} ${tempInfo.band} TEMP LOOP`,
    fluid: input.fluid,
    phase: input.phase,
    temp_min: tempInfo.min,
    temp_max: tempInfo.max,
    temp_band: tempInfo.band,
    sulfur: input.sulfur,
    chloride: input.chloride
  };

  const { data, error: insertError } = await supabase
    .from("corrosion_loops")
    .insert(payload)
    .select()
    .single();

  if (insertError) {
    console.error("Loop insert error:", insertError, payload);
    throw insertError;
  }

  return data;
}

/* ================= AUTO DAMAGE (API RP 970) ================= */
async function autoGenerateDamage(circuit_id) {
  const { error } = await supabase.rpc(
    "auto_damage_for_circuit",
    { cid: circuit_id }
  );

  if (error) {
    console.error("Auto damage error:", error);
    alert("⚠️ Circuit saved but auto-damage failed");
  }
}

/* ================= SAVE ALL ================= */
window.saveAll = async function () {
  try {
    const project_id = document.getElementById("project").value;
    if (!project_id) {
      alert("Select a project");
      return;
    }

    const temperature = Number(document.getElementById("temp").value);
    if (!temperature) {
      alert("Enter temperature");
      return;
    }

    /* LOOP INPUT */
    const loopInput = {
      project_id,
      unit: document.getElementById("unit").value,
      fluid: document.getElementById("fluid").value,
      phase: document.getElementById("phase").value,
      temperature,
      sulfur: document.getElementById("sulfur").checked,
      chloride: document.getElementById("chloride").checked
    };

    /* AUTO LOOP */
    const loop = await getOrCreateLoop(loopInput);

    if (!loop?.id) {
      alert("❌ Loop creation failed");
      return;
    }

    /* AUTO CIRCUIT */
    const { data: circuit, error: circuitError } = await supabase
      .from("circuits")
      .insert({
        loop_id: loop.id,
        circuit_name: document.getElementById("equipment").value,
        material: document.getElementById("material").value,
        temperature,
        sulfur: loopInput.sulfur,
        chloride: loopInput.chloride,
        design_thickness: Number(document.getElementById("design_thk").value),
        minimum_thickness: Number(document.getElementById("min_thk").value)
      })
      .select()
      .single();

    if (circuitError) {
      console.error("Circuit insert error:", circuitError);
      alert("❌ Circuit save failed");
      return;
    }

    /* AUTO DAMAGE */
    await autoGenerateDamage(circuit.id);

    alert("✅ Loop, Circuit & API RP 970 Damage generated successfully");

  } catch (err) {
    console.error("SAVE ERROR FULL:", JSON.stringify(err, null, 2));
    alert(err?.message || "❌ Unexpected error – check console");
  }
};

/* ================= INIT ================= */
loadProjects();
